// <auto-generated />
using System;
using BusTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusTracker.Infrastructure.Migrations
{
    [DbContext(typeof(BusTrackerDbContext))]
    [Migration("20260610181722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BusTracker.Domain.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ViaPoints")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "9861891406",
                            DepartureTime = "6:10 AM",
                            Destination = "Bhubaneswar",
                            IsActive = true,
                            Origin = "Narsinghpur",
                            ReturnTime = "2:15 PM",
                            ServiceName = "Giribala"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "09776359935",
                            DepartureTime = "10:45 AM",
                            Destination = "Narsinghpur",
                            IsActive = true,
                            Origin = "Bhubaneswar",
                            ServiceName = "Pitabali"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "+919777510028",
                            DepartureTime = "11:30 AM",
                            Destination = "Sagar",
                            IsActive = true,
                            Origin = "Bhubaneswar",
                            ServiceName = "Shibani",
                            ViaPoints = "Kanpur"
                        },
                        new
                        {
                            Id = 4,
                            DepartureTime = "9:00 AM",
                            Destination = "Anugul",
                            IsActive = true,
                            Origin = "Bhubaneswar",
                            ServiceName = "Dilkhus",
                            ViaPoints = "Khordha T-Bridge, Narsinghpur, Rusipada"
                        },
                        new
                        {
                            Id = 5,
                            ContactNumber = "9668982220",
                            DepartureTime = "4:45 PM",
                            Destination = "Narsinghpur",
                            IsActive = true,
                            Origin = "Cuttack",
                            ServiceName = "Subhadra Bus"
                        },
                        new
                        {
                            Id = 6,
                            ContactNumber = "+919776353077",
                            DepartureTime = "4:15 AM",
                            Destination = "Kamaladiha",
                            IsActive = true,
                            Origin = "Bhubaneswar",
                            ReturnTime = "11:30 AM",
                            ServiceName = "Jagannath Bus"
                        });
                });

            modelBuilder.Entity("BusTracker.Domain.BusRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminRemarks")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ViaPoints")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BusRegistrations");
                });

            modelBuilder.Entity("BusTracker.Domain.BusStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StopOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("BusStops");
                });

            modelBuilder.Entity("BusTracker.Domain.RouteSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ViaPoints")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RouteSuggestions");
                });

            modelBuilder.Entity("BusTracker.Domain.BusStop", b =>
                {
                    b.HasOne("BusTracker.Domain.Bus", "Bus")
                        .WithMany("Stops")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusTracker.Domain.Bus", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
